name: PR Checks

# Trigger the workflow when a PR is opened or updated to the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  # Define the job for Node.js project checks
  nodejs-checks:
    # The environment where the job will run
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js with the specified version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run Linting (assuming ESLint is used)
      - name: Run lint
        run: npm run lint

      # Run tests (assuming a test script is present in package.json)
      - name: Run tests
        run: npm test

      # Build the project (optional, if you have a build step)
      - name: Build project
        run: npm run build